#!/usr/bin/env python

import struct
import sys
import os

if sys.platform == "win32":
  import os, msvcrt
  msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
  msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)

def send_message(message):
   # Write message size.
  sys.stdout.write(struct.pack('I', len(message)))
  # Write the message itself.
  sys.stdout.write(message)
  sys.stdout.flush()

def read_msg():
  # Read the message length (first 4 bytes).
  text_length_bytes = sys.stdin.read(4)
  if len(text_length_bytes) == 0:
    sys.exit(0)
  # Unpack message length as 4 byte integer.
  text_length = struct.unpack('i', text_length_bytes)[0]
  # Read the text (JSON object) of the message.
  text = sys.stdin.read(text_length).decode('utf-8')
  
  send_message('{"echo": %s}' % text)
  os.startfile('notepad.exe')
  
def Main():
  read_msg();
  sys.exit(0);
  
if __name__ == '__main__':
  Main()